apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: airc-chatbot
  labels:
    app: ui-service
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: ui-service
