apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airc-chatbot

resources:
  - namespace.yaml
  - configmap/shared-config.yaml
  - secrets/shared-secrets.yaml
  - mongodb/deployment.yaml
  - redis/deployment.yaml
  - qdrant/deployment.yaml
